apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ff-pushpin-service
  namespace: {{ .Release.Namespace }}
spec:
  minAvailable: "50%"
  selector:
   matchLabels:
    app: ff-pushpin-service
